# Generated by Django 4.0.4 on 2022-04-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0011_profile_prfile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prfile_pic',
            new_name='profile_pic',
        ),
    ]
